In [25]:
import pandas as pd
df = pd.read_csv('netflix_titles_nov_2019.csv')

In [26]:
df

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show
...,...,...,...,...,...,...,...,...,...,...,...,...
5832,70141644,Mad Ron's Prevues from Hell,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States,"November 1, 2010",1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott...",Movie
5833,70127998,Splatter,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States,"November 18, 2009",2009,TV-14,29 min,Horror Movies,"After committing suicide, a washed-up rocker r...",Movie
5834,70084180,Just Another Love Story,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark,"May 5, 2009",2007,NR,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...,Movie
5835,70157452,Dinner for Five,NaN,NaN,United States,"February 4, 2008",2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo...",TV Show
5836,70053412,To and From New York,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States,"January 1, 2008",2006,NR,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea...",Movie

In [27]:
def create_textual_representation(row):
        textual_representation = f"""Type: {row['type']},
    Title: {row['title']},
    Director: {row['director']},
    Cast: {row['cast']},
    Released: {row['release_year']},
    Genres: {row['listed_in']},
    Description: {row['description']}"""
        return textual_representation

In [28]:
df['textual_representation'] = df.apply(create_textual_representation, axis=1)

In [29]:
df['textual_representation']

0       Type: TV Show,\n    Title: Chocolate,\n    Dir...
1       Type: Movie,\n    Title: Guatemala: Heart of t...
2       Type: Movie,\n    Title: The Zoya Factor,\n   ...
3       Type: Movie,\n    Title: Atlantics,\n    Direc...
4       Type: TV Show,\n    Title: Chip and Potato,\n ...
                              ...
5832    Type: Movie,\n    Title: Mad Ron's Prevues fro...
5833    Type: Movie,\n    Title: Splatter,\n    Direct...
5834    Type: Movie,\n    Title: Just Another Love Sto...
5835    Type: TV Show,\n    Title: Dinner for Five,\n ...
5836    Type: Movie,\n    Title: To and From New York,...
Name: textual_representation, Length: 5837, dtype: object

In [30]:
print(df['textual_representation'].values[0])

Type: TV Show,
    Title: Chocolate,
    Director: nan,
    Cast: Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang Bu-ja, Lee Jae-ryong, Min Jin-woong, Kim Won-hae, Yoo Teo,
    Released: 2019,
    Genres: International TV Shows, Korean TV Shows, Romantic TV Shows,
    Description: Brought together by meaningful meals in the past and present, a doctor and a chef are reacquainted when they begin working at a hospice ward.

In [31]:
import faiss
import requests 
import numpy as np

dim = 4096

index = faiss.IndexFlatL2(dim)
x = np.zeros((len(df['textual_representation']), dim), dtype='float32')

In [35]:
index = faiss.read_index('index')

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char *) at /Users/runner/work/faiss-wheels/faiss-wheels/faiss/faiss/impl/io.cpp:68: Error: 'f' failed: could not open index for reading: No such file or directory

In [38]:
df[df.title.str.contains('Shutter')]

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type,textual_representation
2805,70062814,Shutter,"Banjong Pisanthanakun, Parkpoom Wongpoom","Ananda Everingham, Natthaweeranuch Thongmee, A...",Thailand,"September 5, 2018",2004,TV-MA,96 min,"Horror Movies, International Movies",After killing a young girl in a hit-and-run ac...,Movie,"Type: Movie,\n Title: Shutter,\n Directo..."